"""
SQL Table Loader Module for Hacienda SFTP Downloads
Version: 2.5.0 - Added deduplication for HCM_PERSON_INTF tables by PERSON_NUMBER

This module loads CSV files into SQL Server tables with proper column mapping.
Different source systems (RHUM, FIMAS, HACIENDA, KRONOSPOL, DOE, etc.) have
different CSV column names that must be mapped to the standard database column names.

Based on the original LoadIntfData.py implementation.

Header validation ensures CSV files have the expected columns for each entity/source
combination before attempting to load data.

Change log:
- 2.5.0: Added deduplication for HCM_PERSON_INTF tables by PERSON_NUMBER column to prevent
         PRIMARY KEY violations in stored procedure when source CSV has duplicate person records.
         Also added deduplication for HCM_PERSON_NID_INTF tables by PERSON_NUMBER.
- 2.4.0: Added dual-mapping support via __ALSO__ syntax. Fixed HACIENDA Person Assignment
         to map EMPL_CLASS to both ASSIGNMENT_CATEGORY and WORKER_CATEGORY per LoadIntfData.py
- 2.3.0: Added CSV header validation per reference LoadIntfData.py
"""

SQL_TABLE_LOADER_VERSION = "2.5.0"

import boto3
import io
import re
import csv
from datetime import datetime
from typing import Dict, List, Optional, Tuple


# =============================================================================
# SOURCE ALIASES
# =============================================================================
SOURCE_ALIASES = {
    'HAC88': 'HACIENDA',
    'HACIENDA': 'HACIENDA',
    'RHUM': 'RHUM',
    'FIMAS': 'FIMAS',
    'KRONOSPOL': 'KRONOSPOL',
    'DOE': 'DOE',
    'ADPPOLICIA': 'ADPPOLICIA',
    '911': '911',
    'KRONOSDE': 'KRONOSDE',
    'SEPI': 'SEPI'
}

# PeopleSoft-style sources that need column name transformation
PEOPLESOFT_SOURCES = ['RHUM', 'FIMAS', 'HACIENDA']


# =============================================================================
# EXPECTED CSV HEADERS BY ENTITY AND SOURCE
# =============================================================================
# These define the REQUIRED CSV columns for each entity/source combination.
# Based on LoadIntfData.py reference implementation.
# Format: (entity_type, source) -> [list of required CSV column names]

EXPECTED_CSV_HEADERS = {
    # =========================================================================
    # HCM_PERSON_INTF - Person/Worker base file
    # =========================================================================
    ('HCM_PERSON_INTF', 'RHUM'): ['COUNTRY', 'EMPLID', 'EFFDT', 'START_DATE', 'BIRTHDATE'],
    ('HCM_PERSON_INTF', 'FIMAS'): ['COUNTRY', 'EMPLID', 'EFFDT', 'START_DATE', 'BIRTHDATE'],
    ('HCM_PERSON_INTF', 'HACIENDA'): ['COUNTRY', 'EMPLID', 'EFFDT', 'START_DATE', 'BIRTHDATE'],
    ('HCM_PERSON_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EFFECTIVE_START_DATE',
        'START_DATE', 'DATE_OF_BIRTH', 'EFFECTIVE_END_DATE', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EFFECTIVE_START_DATE',
        'START_DATE', 'DATE_OF_BIRTH', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_INTF', 'ADPPOLICIA'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE', 'START_DATE', 'DATE_OF_BIRTH', 'SOURCE_SYSTEM_OWNER'
    ],

    # =========================================================================
    # HCM_PERSON_ADDRESS_INTF - Address file
    # =========================================================================
    ('HCM_PERSON_ADDRESS_INTF', 'RHUM'): [
        'COUNTRY', 'EMPLID', 'ADDRESS_TYPE', 'EFFDT', 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'ADDRESS4',
        'COUNTY', 'STATE', 'REG_REGION', 'CITY', 'POSTAL', 'EFF_STATUS', 'PER_TYPE', 'EMPL_STATUS'
    ],
    ('HCM_PERSON_ADDRESS_INTF', 'FIMAS'): [
        'COUNTRY', 'EMPLID', 'ADDRESS_TYPE', 'EFFDT', 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'ADDRESS4',
        'COUNTY', 'STATE', 'REG_REGION', 'CITY', 'POSTAL', 'EFF_STATUS', 'PER_TYPE', 'EMPL_STATUS'
    ],
    ('HCM_PERSON_ADDRESS_INTF', 'HACIENDA'): [
        'COUNTRY', 'EMPLID', 'ADDRESS_TYPE', 'EFFDT', 'ADDRESS1', 'ADDRESS2', 'ADDRESS3', 'ADDRESS4',
        'COUNTY', 'STATE', 'REG_REGION', 'CITY', 'POSTAL', 'EFF_STATUS', 'PER_TYPE', 'EMPL_STATUS'
    ],
    ('HCM_PERSON_ADDRESS_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ADDRESS_TYPE', 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE', 'COUNTRY', 'ADDRESS_LINE_1', 'ADDRESS_LINE_2', 'ADDRESS_LINE_3',
        'ADDRESS_LINE_4', 'REGION_1', 'REGION_2', 'REGION_3', 'TOWN_OR_CITY', 'POSTAL_CODE',
        'LONG_POSTAL_CODE', 'PRIMARY_FLAG', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_ADDRESS_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ADDRESS_TYPE', 'EFFECTIVE_START_DATE',
        'COUNTRY', 'ADDRESS_LINE_1', 'ADDRESS_LINE_2', 'REGION_1', 'REGION_2', 'TOWN_OR_CITY',
        'POSTAL_CODE', 'PRIMARY_FLAG', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_ADDRESS_INTF', 'ADPPOLICIA'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ADDRESS_TYPE', 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE', 'COUNTRY', 'ADDRESS_LINE_1', 'ADDRESS_LINE_2', 'REGION_2',
        'TOWN_OR_CITY', 'POSTAL_CODE', 'SOURCE_SYSTEM_OWNER'
    ],

    # =========================================================================
    # HCM_PERSON_ASSIGNMENT_INTF - Assignment file (CRITICAL - has EMPL_STATUS)
    # =========================================================================
    ('HCM_PERSON_ASSIGNMENT_INTF', 'RHUM'): [
        'COUNTRY', 'EMPLID', 'GEO_CODE', 'HIRE_DT', 'REHIRE_RECOMMENDATION', 'TERMINATION_DT',
        'PIN_NUM', 'PER_TYPE', 'PER_STATUS', 'ACTION', 'ACTION_REASON', 'EFFDT', 'EFFSEQ',
        'EMPL_STATUS', 'LAST_DATE_WORKED', 'BUSINESS_UNIT', 'ORIG_HIRE_DT', 'POSITION_NBR',
        'POSITION_OVERRIDE', 'JOBCODE', 'SAL_ADMIN_PLAN', 'GRADE', 'STEP', 'DEPTID',
        'JOB_REPORTING', 'LOCATION', 'PAYGROUP', 'COMPANY', 'REG_TEMP', 'FULL_PART_TIME',
        'REHIRE_DT', 'HOURLY_RT', 'STD_HOURS', 'COMP_FREQUENCY', 'LANG_CD', 'EMPL_TYPE',
        'FTE', 'EMPL_CLASS', 'ACTION_DT'
    ],
    ('HCM_PERSON_ASSIGNMENT_INTF', 'FIMAS'): [
        'COUNTRY', 'EMPLID', 'GEO_CODE', 'HIRE_DT', 'REHIRE_RECOMMENDATION', 'TERMINATION_DT',
        'PIN_NUM', 'PER_TYPE', 'PER_STATUS', 'ACTION', 'ACTION_REASON', 'EFFDT', 'EFFSEQ',
        'EMPL_STATUS', 'LAST_DATE_WORKED', 'BUSINESS_UNIT', 'ORIG_HIRE_DT', 'POSITION_NBR',
        'POSITION_OVERRIDE', 'JOBCODE', 'SAL_ADMIN_PLAN', 'GRADE', 'STEP', 'DEPTID',
        'JOB_REPORTING', 'LOCATION', 'PAYGROUP', 'COMPANY', 'REG_TEMP', 'FULL_PART_TIME',
        'REHIRE_DT', 'HOURLY_RT', 'STD_HOURS', 'COMP_FREQUENCY', 'LANG_CD', 'EMPL_TYPE',
        'FTE', 'EMPL_CLASS', 'ACTION_DT', 'WORKER_CATEGORY'
    ],
    ('HCM_PERSON_ASSIGNMENT_INTF', 'HACIENDA'): [
        'COUNTRY', 'EMPLID', 'GEO_CODE', 'HIRE_DT', 'REHIRE_RECOMMENDATION', 'TERMINATION_DT',
        'PIN_NUM', 'PER_TYPE', 'PER_STATUS', 'ACTION', 'ACTION_REASON', 'EFFDT', 'EFFSEQ',
        'EMPL_STATUS', 'LAST_DATE_WORKED', 'BUSINESS_UNIT', 'ORIG_HIRE_DT', 'POSITION_NBR',
        'POSITION_OVERRIDE', 'JOBCODE', 'SAL_ADMIN_PLAN', 'GRADE', 'STEP', 'DEPTID',
        'JOB_REPORTING', 'LOCATION', 'PAYGROUP', 'COMPANY', 'REG_TEMP', 'FULL_PART_TIME',
        'REHIRE_DT', 'HOURLY_RT', 'STD_HOURS', 'COMP_FREQUENCY', 'LANG_CD', 'EMPL_TYPE',
        'FTE', 'EMPL_CLASS', 'ACTION_DT'
    ],
    ('HCM_PERSON_ASSIGNMENT_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'HIRE_DATE', 'REHIRE_RECOMMENDATION',
        'TERMINATION_DATE', 'ACTION_CODE', 'ACTION_REASON', 'EFFECTIVE_DATE', 'EFFECTIVE_SEQUENCE',
        'ASSIGNMENT_STATUS_TYPE', 'LAST_WORKING_DATE', 'BUSINESS_UNIT', 'POSITION_CODE',
        'POSITION_OVERRIDE', 'JOB_CODE', 'GRADE_CODE', 'DEPARTMENT_NAME', 'LOCATION_CODE',
        'REGULAR_TEMPORARY', 'FULL_PART_TIME', 'FREQUENCY', 'ASSIGNMENT_CATEGORY', 'FTE',
        'HOURLY_SALARIED_CODE', 'WORKING_HOURS'
    ],
    ('HCM_PERSON_ASSIGNMENT_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'LEGAL_ENTITY', 'HIRE_DATE',
        'REHIRE_RECOMMENDATION_FLAG', 'PROJECTED_TERMINATION_DATE', 'ASSIGNMENT_NUMBER',
        'SYSTEM_PERSON_TYPE', 'USER_PERSON_TYPE', 'PRIMARY_WORK_RELATION', 'PRIMARY_ASSIGNMENT',
        'ACTION_CODE', 'EFFECTIVE_DATE', 'EFFECTIVE_SEQUENCE', 'ASSIGNMENT_STATUS_TYPE',
        'ACTUAL_TERMINATION_DATE', 'LAST_WORKING_DATE', 'BUSINESS_UNIT', 'POSITION_CODE',
        'JOB_CODE', 'GRADE_CODE', 'DEPARTMENT_NAME', 'LOCATION_CODE', 'WORKER_CATEGORY',
        'ASSIGNMENT_CATEGORY', 'PERMANENT_TEMPORARY', 'FULL_PART_TIME', 'HOURLY_SALARIED_CODE',
        'NORMAL_HOURS', 'FREQUENCY', 'FTE', 'UNION_NAME', 'CONTRACT_NUMBER', 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1'
    ],

    # =========================================================================
    # HCM_PERSON_NAME_INTF - Name file
    # =========================================================================
    ('HCM_PERSON_NAME_INTF', 'RHUM'): ['COUNTRY', 'EMPLID', 'EFFDT', 'FIRST_NAME', 'LAST_NAME'],
    ('HCM_PERSON_NAME_INTF', 'FIMAS'): ['COUNTRY', 'EMPLID', 'EFFDT', 'FIRST_NAME', 'LAST_NAME'],
    ('HCM_PERSON_NAME_INTF', 'HACIENDA'): ['COUNTRY', 'EMPLID', 'EFFDT', 'FIRST_NAME', 'LAST_NAME'],
    ('HCM_PERSON_NAME_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'NAME_TYPE', 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE', 'LAST_NAME', 'FIRST_NAME', 'MIDDLE_NAMES', 'TITLE', 'PRE_NAME_ADJUNCT',
        'SUFFIX', 'KNOWN_AS', 'PREVIOUS_LAST_NAME', 'HONORS', 'MILITARY_RANK', 'CHAR_SET_CONTEXT',
        'ACADEMIC_TITLE', 'BIRTHNAME_PREFIX', 'BIRTHNAME', 'BIRTHNAME_SUFFIX', 'STD_MANNER_OF_ADDRESS',
        'EXTEND_MANNER_ADDRESS', 'REPORT_FIRST_NAME', 'REPORT_LAST_NAME', 'MAIDEN_NAME',
        'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_NAME_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'NAME_TYPE', 'EFFECTIVE_START_DATE',
        'LAST_NAME', 'FIRST_NAME', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_NAME_INTF', 'ADPPOLICIA'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'NAME_TYPE', 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE', 'LAST_NAME', 'FIRST_NAME', 'MIDDLE_NAME', 'SUFFIX',
        'PREVIOUS_LAST_NAME', 'SOURCE_SYSTEM_OWNER'
    ],

    # =========================================================================
    # HCM_PERSON_NID_INTF - National ID file
    # =========================================================================
    ('HCM_PERSON_NID_INTF', 'RHUM'): [
        'COUNTRY', 'EMPLID', 'NATIONAL_ID_TYPE', 'NATIONAL_ID', 'NID_COUNTRY',
        'US_WORK_ELIGIBILTY', 'PAYGROUP'
    ],
    ('HCM_PERSON_NID_INTF', 'FIMAS'): [
        'COUNTRY', 'EMPLID', 'NATIONAL_ID_TYPE', 'NATIONAL_ID', 'NID_COUNTRY',
        'US_WORK_ELIGIBILTY', 'PAYGROUP'
    ],
    ('HCM_PERSON_NID_INTF', 'HACIENDA'): [
        'COUNTRY', 'EMPLID', 'NATIONAL_ID_TYPE', 'NATIONAL_ID', 'NID_COUNTRY',
        'US_WORK_ELIGIBILTY', 'PAYGROUP'
    ],
    ('HCM_PERSON_NID_INTF', 'KRONOSPOL'): ['Country Code', 'Person Number', 'Identifier Number'],
    ('HCM_PERSON_NID_INTF', 'KRONOSDE'): ['Country Code', 'Person Number', 'Identifier Number'],
    ('HCM_PERSON_NID_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'LEGISLATION_CODE',
        'NATIONAL_IDENTIFIER_TYPE', 'NATIONAL_IDENTIFIER_NUMBER', 'PRIMARY_FLAG'
    ],
    ('HCM_PERSON_NID_INTF', 'ADPPOLICIA'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'LEGISLATION_CODE',
        'NATIONAL_IDENTIFIER_TYPE', 'NATIONAL_IDENTIFIER_NUMBER', 'PRIMARY_FLAG', 'SOURCE_SYSTEM_OWNER'
    ],

    # =========================================================================
    # HCM_PERSON_SUPERVISOR_INTF - Supervisor file
    # =========================================================================
    ('HCM_PERSON_SUPERVISOR_INTF', 'RHUM'): [
        'COUNTRY', 'PERSON_NUMBER', 'MANAGER_TYPE', 'ACTION', 'ACTION_REASON', 'MANAGER_PERSON_NUMBER'
    ],
    ('HCM_PERSON_SUPERVISOR_INTF', 'FIMAS'): [
        'COUNTRY', 'EMPLID', 'EFFDT', 'EMPLID2', 'ACTION', 'ACTION_REASON', 'DESCR',
        'REPORTS_TO', 'TAX_LOCATION_CD', 'PAYGROUP', 'COMPANY'
    ],
    ('HCM_PERSON_SUPERVISOR_INTF', 'HACIENDA'): [
        'COUNTRY', 'EMPLID', 'EFFDT', 'EMPLID2', 'ACTION', 'ACTION_REASON', 'DESCR',
        'REPORTS_TO', 'TAX_LOCATION_CD', 'PAYGROUP', 'COMPANY'
    ],
    ('HCM_PERSON_SUPERVISOR_INTF', '911'): ['PERSON_NUMBER', 'SupervisorPersonNumber'],
    ('HCM_PERSON_SUPERVISOR_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ASSIGNMENT_NUMBER', 'LEGAL_ENTITY',
        'MANAGER_TYPE', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE', 'ACTION_CODE', 'ACTION_REASON',
        'MANAGER_PERSON_NUMBER', 'MANAGER_ASSIGNMENT_NUMBER', 'MANAGER_LEGAL_ENTITY', 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_SUPERVISOR_INTF', 'KRONOSDE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ASSIGNMENT_NUMBER', 'LEGAL_ENTITY',
        'MANAGER_TYPE', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE', 'ACTION_CODE', 'ACTION_REASON',
        'MANAGER_PERSON_NUMBER', 'MANAGER_ASSIGNMENT_NUMBER', 'MANAGER_LEGAL_ENTITY', 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
        # Plus many ATTRIBUTE2-30, ATTRIBUTE_NUMBER1-20, ATTRIBUTE_DATE1-15 (omitted for brevity)
    ],
    ('HCM_PERSON_SUPERVISOR_INTF', 'SEPI'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'ASSIGNMENT_NUMBER', 'LEGAL_ENTITY',
        'MANAGER_TYPE', 'EFFECTIVE_START_DATE', 'EFFECTIVE_END_DATE', 'ACTION_CODE', 'ACTION_REASON',
        'MANAGER_PERSON_NUMBER', 'MANAGER_ASSIGNMENT_NUMBER', 'MANAGER_LEGAL_ENTITY', 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
        # Plus many ATTRIBUTE2-30, ATTRIBUTE_NUMBER1-20, ATTRIBUTE_DATE1-15 (omitted for brevity)
    ],

    # =========================================================================
    # HCM_PERSON_EMAIL_INTF - Email file
    # =========================================================================
    ('HCM_PERSON_EMAIL_INTF', 'RHUM'): ['COUNTRY', 'EMPLID', 'E_ADDR_TYPE', 'Email_ADDR', 'EFFDT'],
    ('HCM_PERSON_EMAIL_INTF', 'FIMAS'): ['COUNTRY', 'EMPLID', 'E_ADDR_TYPE', 'EmailADDR', 'EFFDT'],
    ('HCM_PERSON_EMAIL_INTF', 'HACIENDA'): ['COUNTRY', 'EMPLID', 'E_ADDR_TYPE', 'EmailADDR', 'EFFDT'],
    ('HCM_PERSON_EMAIL_INTF', 'KRONOSPOL'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EMAIL_TYPE',
        'EFFECTIVE_START_DATE', 'EMAIL_ADDRESS', 'PRIMARY_FLAG', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_EMAIL_INTF', 'DOE'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EMAIL_TYPE', 'DATE_FROM',
        'EMAIL_ADDRESS', 'PRIMARY_FLAG', 'ATTRIBUTE_CATEGORY', 'ATTRIBUTE1'
    ],
    ('HCM_PERSON_EMAIL_INTF', 'ADPPOLICIA'): [
        'COUNTRY_CODE', 'SWIFT_PERSON_TYPE', 'PERSON_NUMBER', 'EMAIL_TYPE', 'DATE_FROM',
        'DATE_TO', 'EMAIL_ADDRESS', 'PRIMARY_FLAG', 'SOURCE_SYSTEM_OWNER'
    ],

    # =========================================================================
    # HCM_SENIORITY_INTF - Seniority file
    # =========================================================================
    ('HCM_SENIORITY_INTF', 'RHUM'): ['PERSON_NUMBER', 'SENIORITY_DATE_CODE', 'ENTRY_DATE'],
    ('HCM_SENIORITY_INTF', 'FIMAS'): ['PERSON_NUMBER', 'SENIORITY_DATE_CODE', 'ENTRY_DATE'],
    ('HCM_SENIORITY_INTF', 'HACIENDA'): ['PERSON_NUMBER', 'SENIORITY_DATE_CODE', 'ENTRY_DATE'],
}


# =============================================================================
# COLUMN MAPPINGS BY ENTITY AND SOURCE
# =============================================================================
# Format: (entity_type, source) -> {csv_column: db_column, ...}
# These mappings define how CSV columns map to database columns for each combination

COLUMN_MAPPINGS = {
    # =========================================================================
    # HCM_PERSON_INTF - Person/Worker base file
    # =========================================================================
    ('HCM_PERSON_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'START_DATE': 'START_DATE',
        'BIRTHDATE': 'DATE_OF_BIRTH',
    },
    ('HCM_PERSON_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'START_DATE': 'START_DATE',
        'BIRTHDATE': 'DATE_OF_BIRTH',
    },
    ('HCM_PERSON_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'START_DATE': 'START_DATE',
        'BIRTHDATE': 'DATE_OF_BIRTH',
    },
    ('HCM_PERSON_INTF', 'KRONOSPOL'): {
        # Direct mapping - CSV columns match DB columns
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'START_DATE': 'START_DATE',
        'DATE_OF_BIRTH': 'DATE_OF_BIRTH',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'START_DATE': 'START_DATE',
        'DATE_OF_BIRTH': 'DATE_OF_BIRTH',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_INTF', 'ADPPOLICIA'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'START_DATE': 'START_DATE',
        'DATE_OF_BIRTH': 'DATE_OF_BIRTH',
        'SOURCE_SYSTEM_OWNER': 'SOURCE_SYSTEM_OWNER',
    },

    # =========================================================================
    # HCM_PERSON_ADDRESS_INTF - Address file
    # =========================================================================
    ('HCM_PERSON_ADDRESS_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'ADDRESS1': 'ADDRESS_LINE_1',
        'ADDRESS2': 'ADDRESS_LINE_2',
        'ADDRESS3': 'ADDRESS_LINE_3',
        'ADDRESS4': 'ADDRESS_LINE_4',
        'COUNTY': 'REGION_1',
        'STATE': 'REGION_2',
        'REG_REGION': 'COUNTRY',
        'CITY': 'TOWN_OR_CITY',
        'POSTAL': 'POSTAL_CODE',
        'EFF_STATUS': 'EFF_STATUS',
        'EMPL_STATUS': 'EMPL_STATUS',
    },
    ('HCM_PERSON_ADDRESS_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'ADDRESS1': 'ADDRESS_LINE_1',
        'ADDRESS2': 'ADDRESS_LINE_2',
        'ADDRESS3': 'ADDRESS_LINE_3',
        'ADDRESS4': 'ADDRESS_LINE_4',
        'COUNTY': 'REGION_1',
        'STATE': 'REGION_2',
        'REG_REGION': 'COUNTRY',
        'CITY': 'TOWN_OR_CITY',
        'POSTAL': 'POSTAL_CODE',
        'EFF_STATUS': 'EFF_STATUS',
        'EMPL_STATUS': 'EMPL_STATUS',
    },
    ('HCM_PERSON_ADDRESS_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'ADDRESS1': 'ADDRESS_LINE_1',
        'ADDRESS2': 'ADDRESS_LINE_2',
        'ADDRESS3': 'ADDRESS_LINE_3',
        'ADDRESS4': 'ADDRESS_LINE_4',
        'COUNTY': 'REGION_1',
        'STATE': 'REGION_2',
        'REG_REGION': 'COUNTRY',
        'CITY': 'TOWN_OR_CITY',
        'POSTAL': 'POSTAL_CODE',
        'EFF_STATUS': 'EFF_STATUS',
        'EMPL_STATUS': 'EMPL_STATUS',
    },
    ('HCM_PERSON_ADDRESS_INTF', 'KRONOSPOL'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'COUNTRY': 'COUNTRY',
        'ADDRESS_LINE_1': 'ADDRESS_LINE_1',
        'REGION_1': 'REGION_1',
        'REGION_2': 'REGION_2',
        'TOWN_OR_CITY': 'TOWN_OR_CITY',
        'POSTAL_CODE': 'POSTAL_CODE',
        'ADDRESS_LINE_2': 'ADDRESS_LINE_2',
        'ADDRESS_LINE_3': 'ADDRESS_LINE_3',
        'ADDRESS_LINE_4': 'ADDRESS_LINE_4',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'LONG_POSTAL_CODE': 'LONG_POSTAL_CODE',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_ADDRESS_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'COUNTRY': 'COUNTRY',
        'ADDRESS_LINE_1': 'ADDRESS_LINE_1',
        'REGION_1': 'REGION_1',
        'REGION_2': 'REGION_2',
        'TOWN_OR_CITY': 'TOWN_OR_CITY',
        'POSTAL_CODE': 'POSTAL_CODE',
        'ADDRESS_LINE_2': 'ADDRESS_LINE_2',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_ADDRESS_INTF', 'ADPPOLICIA'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'ADDRESS_TYPE': 'ADDRESS_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'COUNTRY': 'COUNTRY',
        'ADDRESS_LINE_1': 'ADDRESS_LINE_1',
        'ADDRESS_LINE_2': 'ADDRESS_LINE_2',
        'REGION_2': 'REGION_2',
        'TOWN_OR_CITY': 'TOWN_OR_CITY',
        'POSTAL_CODE': 'POSTAL_CODE',
        'SOURCE_SYSTEM_OWNER': 'SOURCE_SYSTEM_OWNER',
    },

    # =========================================================================
    # HCM_PERSON_ASSIGNMENT_INTF - Assignment file
    # =========================================================================
    ('HCM_PERSON_ASSIGNMENT_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'PER_TYPE': 'SWIFT_PERSON_TYPE',
        'EMPLID': 'PERSON_NUMBER',
        'HIRE_DT': 'HIRE_DATE',
        'EFFDT': 'EFFECTIVE_DATE',
        'EFFSEQ': 'EFFECTIVE_SEQUENCE',
        'EMPL_STATUS': 'ASSIGNMENT_STATUS_TYPE',
        'BUSINESS_UNIT': 'BUSINESS_UNIT',
        'LOCATION': 'LOCATION_CODE',
        'ACTION': 'ACTION_CODE',
        'ACTION_REASON': 'ACTION_REASON',
        'FULL_PART_TIME': 'FULL_PART_TIME',
        'REG_TEMP': 'REGULAR_TEMPORARY',
        'HOURLY_RT': 'HOURLY_RATE',
        'REHIRE_DT': 'REHIRE_DATE',
        'LAST_DATE_WORKED': 'LAST_WORKING_DATE',
        'POSITION_NBR': 'POSITION_CODE',
        'TERMINATION_DT': 'TERMINATION_DATE',
        'STD_HOURS': 'WORKING_HOURS',
        'PAYGROUP': 'PAY_GROUP',
        'JOBCODE': 'JOB_CODE',
        'POSITION_OVERRIDE': 'POSITION_OVERRIDE',
        'SAL_ADMIN_PLAN': 'SAL_ADMIN_PLAN',
        'EMPL_TYPE': 'HOURLY_SALARIED_CODE',
        'COMP_FREQUENCY': 'FREQUENCY',
        'COMPANY': 'COMPANY',
        'FTE': 'FTE',
        'ORIG_HIRE_DT': 'ORIG_HIRE_DT',
        'DEPTID': 'DEPTID',
        'GRADE': 'GRADE',
        'EMPL_CLASS': 'ASSIGNMENT_CATEGORY',
        'ACTION_DT': 'ACTION_DT',
        # Note: WORKER_CATEGORY maps from EMPL_CLASS in original code
    },
    ('HCM_PERSON_ASSIGNMENT_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'PER_TYPE': 'SWIFT_PERSON_TYPE',
        'EMPLID': 'PERSON_NUMBER',
        'HIRE_DT': 'HIRE_DATE',
        'EFFDT': 'EFFECTIVE_DATE',
        'EFFSEQ': 'EFFECTIVE_SEQUENCE',
        'EMPL_STATUS': 'ASSIGNMENT_STATUS_TYPE',  # Reference uses EMPL_STATUS, not ASSIGNMENT_STATUS_TYPE column
        'BUSINESS_UNIT': 'BUSINESS_UNIT',
        'LOCATION': 'LOCATION_CODE',
        'ACTION': 'ACTION_CODE',
        'ACTION_REASON': 'ACTION_REASON',
        'FULL_PART_TIME': 'FULL_PART_TIME',
        'REG_TEMP': 'REGULAR_TEMPORARY',
        'HOURLY_RT': 'HOURLY_RATE',
        'REHIRE_DT': 'REHIRE_DATE',
        'LAST_DATE_WORKED': 'LAST_WORKING_DATE',
        'POSITION_NBR': 'POSITION_CODE',
        'TERMINATION_DT': 'TERMINATION_DATE',
        'STD_HOURS': 'WORKING_HOURS',
        'PAYGROUP': 'PAY_GROUP',
        'JOBCODE': 'JOB_CODE',
        'POSITION_OVERRIDE': 'POSITION_OVERRIDE',
        'SAL_ADMIN_PLAN': 'SAL_ADMIN_PLAN',
        'EMPL_TYPE': 'HOURLY_SALARIED_CODE',
        'COMP_FREQUENCY': 'FREQUENCY',
        'COMPANY': 'COMPANY',
        'FTE': 'FTE',
        'ORIG_HIRE_DT': 'ORIG_HIRE_DT',
        'DEPTID': 'DEPTID',
        'GRADE': 'GRADE',
        'EMPL_CLASS': 'ASSIGNMENT_CATEGORY',
        'WORKER_CATEGORY': 'WORKER_CATEGORY',
        'ACTION_DT': 'ACTION_DT',
    },
    ('HCM_PERSON_ASSIGNMENT_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'PER_TYPE': 'SWIFT_PERSON_TYPE',
        'EMPLID': 'PERSON_NUMBER',
        'HIRE_DT': 'HIRE_DATE',
        'REHIRE_RECOMMENDATION': 'REHIRE_RECOMMENDATION',
        'EFFDT': 'EFFECTIVE_DATE',
        'EFFSEQ': 'EFFECTIVE_SEQUENCE',
        'EMPL_STATUS': 'ASSIGNMENT_STATUS_TYPE',  # Reference uses EMPL_STATUS, not ASSIGNMENT_STATUS_TYPE column
        'BUSINESS_UNIT': 'BUSINESS_UNIT',
        'LOCATION': 'LOCATION_CODE',
        'ACTION': 'ACTION_CODE',
        'ACTION_REASON': 'ACTION_REASON',
        'FULL_PART_TIME': 'FULL_PART_TIME',
        'REG_TEMP': 'REGULAR_TEMPORARY',
        'HOURLY_RT': 'HOURLY_RATE',
        'REHIRE_DT': 'REHIRE_DATE',
        'LAST_DATE_WORKED': 'LAST_WORKING_DATE',
        'POSITION_NBR': 'POSITION_CODE',
        'TERMINATION_DT': 'TERMINATION_DATE',
        'STD_HOURS': 'WORKING_HOURS',
        'PAYGROUP': 'PAY_GROUP',
        'JOBCODE': 'JOB_CODE',
        'POSITION_OVERRIDE': 'POSITION_OVERRIDE',
        'SAL_ADMIN_PLAN': 'SAL_ADMIN_PLAN',
        'EMPL_TYPE': 'HOURLY_SALARIED_CODE',
        'COMP_FREQUENCY': 'FREQUENCY',
        'COMPANY': 'COMPANY',
        'FTE': 'FTE',
        'ORIG_HIRE_DT': 'ORIG_HIRE_DT',
        'DEPTID': 'DEPTID',
        'GRADE': 'GRADE',
        'EMPL_CLASS': 'ASSIGNMENT_CATEGORY',
        'ACTION_DT': 'ACTION_DT',
        # Note: EMPL_CLASS also maps to WORKER_CATEGORY per LoadIntfData.py line 489
        # Use special dual-mapping syntax: source column ends with __ALSO__target
        'EMPL_CLASS__ALSO__WORKER_CATEGORY': 'WORKER_CATEGORY',
    },
    ('HCM_PERSON_ASSIGNMENT_INTF', 'KRONOSPOL'): {
        # Direct mapping for Oracle HCM style columns
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'HIRE_DATE': 'HIRE_DATE',
        'ACTION_CODE': 'ACTION_CODE',
        'EFFECTIVE_DATE': 'EFFECTIVE_DATE',
        'EFFECTIVE_SEQUENCE': 'EFFECTIVE_SEQUENCE',
        'ASSIGNMENT_STATUS_TYPE': 'ASSIGNMENT_STATUS_TYPE',
        'BUSINESS_UNIT': 'BUSINESS_UNIT',
        'LOCATION_CODE': 'LOCATION_CODE',
        'ACTION_REASON': 'ACTION_REASON',
        'FULL_PART_TIME': 'FULL_PART_TIME',
        'PERMANENT_TEMPORARY': 'REGULAR_TEMPORARY',
        'LAST_WORKING_DATE': 'LAST_WORKING_DATE',
        'POSITION_CODE': 'POSITION_CODE',
        'TERMINATION_DATE': 'TERMINATION_DATE',
        'WORKING_HOURS': 'WORKING_HOURS',
        'JOB_CODE': 'JOB_CODE',
        'POSITION_OVERRIDE': 'POSITION_OVERRIDE',
        'HOURLY_SALARIED_CODE': 'HOURLY_SALARIED_CODE',
        'FREQUENCY': 'FREQUENCY',
        'FTE': 'FTE',
        'DEPARTMENT_NAME': 'DEPTID',
        'GRADE_CODE': 'GRADE',
        'ASSIGNMENT_CATEGORY': 'ASSIGNMENT_CATEGORY',
        'WORKER_CATEGORY': 'WORKER_CATEGORY',
        'MANAGER_FLAG': 'MANAGER_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_ASSIGNMENT_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'LEGAL_ENTITY': 'LEGAL_ENTITY',
        'HIRE_DATE': 'HIRE_DATE',
        'ASSIGNMENT_NUMBER': 'ASSIGNMENT_NUMBER',
        'SYSTEM_PERSON_TYPE': 'SYSTEM_PERSON_TYPE',
        'USER_PERSON_TYPE': 'USER_PERSON_TYPE',
        'PRIMARY_WORK_RELATION': 'PRIMARY_WORK_RELATION',
        'PRIMARY_ASSIGNMENT': 'PRIMARY_ASSIGNMENT',
        'ACTION_CODE': 'ACTION_CODE',
        'EFFECTIVE_DATE': 'EFFECTIVE_DATE',
        'EFFECTIVE_SEQUENCE': 'EFFECTIVE_SEQUENCE',
        'ASSIGNMENT_STATUS_TYPE': 'ASSIGNMENT_STATUS_TYPE',
        'LAST_WORKING_DATE': 'LAST_WORKING_DATE',
        'BUSINESS_UNIT': 'BUSINESS_UNIT',
        'LOCATION_CODE': 'LOCATION_CODE',
        'FULL_PART_TIME': 'FULL_PART_TIME',
        'JOB_CODE': 'JOB_CODE',
        'HOURLY_SALARIED_CODE': 'HOURLY_SALARIED_CODE',
        'FREQUENCY': 'FREQUENCY',
        'FTE': 'FTE',
        'UNION_NAME': 'UNION_NAME',
        'CONTRACT_NUMBER': 'CONTRACT_NUMBER',
        'GRADE_CODE': 'GRADE_CODE',
        'DEPARTMENT_NAME': 'DEPARTMENT_NAME',
        'WORKER_CATEGORY': 'WORKER_CATEGORY',
        'ASSIGNMENT_CATEGORY': 'ASSIGNMENT_CATEGORY',
        'PROJECTED_TERMINATION_DATE': 'PROJECTED_TERMINATION_DATE',
        'ACTUAL_TERMINATION_DATE': 'ACTUAL_TERMINATION_DATE',
        'POSITION_CODE': 'POSITION_CODE',
        'PERMANENT_TEMPORARY': 'REGULAR_TEMPORARY',
        'NORMAL_HOURS': 'WORKING_HOURS',
    },

    # =========================================================================
    # HCM_PERSON_NAME_INTF - Name file
    # =========================================================================
    ('HCM_PERSON_NAME_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'FIRST_NAME': 'FIRST_NAME',
        'LAST_NAME': 'LAST_NAME',
    },
    ('HCM_PERSON_NAME_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'FIRST_NAME': 'FIRST_NAME',
        'LAST_NAME': 'LAST_NAME',
    },
    ('HCM_PERSON_NAME_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'FIRST_NAME': 'FIRST_NAME',
        'LAST_NAME': 'LAST_NAME',
    },
    ('HCM_PERSON_NAME_INTF', 'KRONOSPOL'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'NAME_TYPE': 'NAME_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'LAST_NAME': 'LAST_NAME',
        'FIRST_NAME': 'FIRST_NAME',
        'MIDDLE_NAMES': 'MIDDLE_NAME',
        'TITLE': 'TITLE',
        'PRE_NAME_ADJUNCT': 'PRE_NAME_ADJUNCT',
        'SUFFIX': 'SUFFIX',
        'KNOWN_AS': 'KNOWN_AS',
        'PREVIOUS_LAST_NAME': 'PREVIOUS_LAST_NAME',
        'HONORS': 'HONORS',
        'MILITARY_RANK': 'MILITARY_RANK',
        'CHAR_SET_CONTEXT': 'CHAR_SET_CONTEXT',
        'ACADEMIC_TITLE': 'ACADEMIC_TITLE',
        'BIRTHNAME_PREFIX': 'BIRTHNAME_PREFIX',
        'BIRTHNAME': 'BIRTHNAME',
        'BIRTHNAME_SUFFIX': 'BIRTHNAME_SUFFIX',
        'STD_MANNER_OF_ADDRESS': 'STD_MANNER_OF_ADDRESS',
        'EXTEND_MANNER_ADDRESS': 'EXTEND_MANNER_ADDRESS',
        'REPORT_FIRST_NAME': 'REPORT_FIRST_NAME',
        'REPORT_LAST_NAME': 'REPORT_LAST_NAME',
        'MAIDEN_NAME': 'MAIDEN_NAME',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_NAME_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'NAME_TYPE': 'NAME_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'LAST_NAME': 'LAST_NAME',
        'FIRST_NAME': 'FIRST_NAME',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
        'X': 'X',
    },
    ('HCM_PERSON_NAME_INTF', 'ADPPOLICIA'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'NAME_TYPE': 'NAME_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'LAST_NAME': 'LAST_NAME',
        'FIRST_NAME': 'FIRST_NAME',
        'MIDDLE_NAME': 'MIDDLE_NAME',
        'SUFFIX': 'SUFFIX',
        'PREVIOUS_LAST_NAME': 'PREVIOUS_LAST_NAME',
        'SOURCE_SYSTEM_OWNER': 'SOURCE_SYSTEM_OWNER',
    },

    # =========================================================================
    # HCM_PERSON_NID_INTF - National ID file
    # =========================================================================
    ('HCM_PERSON_NID_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'NATIONAL_ID_TYPE': 'NATIONAL_IDENTIFIER_TYPE',
        'NATIONAL_ID': 'NATIONAL_IDENTIFIER_NUMBER',
        'NID_COUNTRY': 'PRIMARY_FLAG',
        'US_WORK_ELIGIBILTY': 'US_WORK_ELIGIBILITY',
        'PAYGROUP': 'PAYGROUP',
    },
    ('HCM_PERSON_NID_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'NATIONAL_ID_TYPE': 'NATIONAL_IDENTIFIER_TYPE',
        'NATIONAL_ID': 'NATIONAL_IDENTIFIER_NUMBER',
        'NID_COUNTRY': 'PRIMARY_FLAG',
        'US_WORK_ELIGIBILTY': 'US_WORK_ELIGIBILITY',
        'PAYGROUP': 'PAYGROUP',
    },
    ('HCM_PERSON_NID_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'NATIONAL_ID_TYPE': 'NATIONAL_IDENTIFIER_TYPE',
        'NATIONAL_ID': 'NATIONAL_IDENTIFIER_NUMBER',
        'NID_COUNTRY': 'PRIMARY_FLAG',
        'US_WORK_ELIGIBILTY': 'US_WORK_ELIGIBILITY',
        'PAYGROUP': 'PAYGROUP',
    },
    ('HCM_PERSON_NID_INTF', 'KRONOSPOL'): {
        'Country Code': 'COUNTRY_CODE',
        'Person Number': 'PERSON_NUMBER',
        'Identifier Number': 'NATIONAL_IDENTIFIER_NUMBER',
    },
    ('HCM_PERSON_NID_INTF', 'KRONOSDE'): {
        'Country Code': 'COUNTRY_CODE',
        'Person Number': 'PERSON_NUMBER',
        'Identifier Number': 'NATIONAL_IDENTIFIER_NUMBER',
    },
    ('HCM_PERSON_NID_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'LEGISLATION_CODE': 'LEGISLATION_CODE',
        'NATIONAL_IDENTIFIER_TYPE': 'NATIONAL_IDENTIFIER_TYPE',
        'NATIONAL_IDENTIFIER_NUMBER': 'NATIONAL_IDENTIFIER_NUMBER',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
    },
    ('HCM_PERSON_NID_INTF', 'ADPPOLICIA'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'LEGISLATION_CODE': 'LEGISLATION_CODE',
        'NATIONAL_IDENTIFIER_TYPE': 'NATIONAL_IDENTIFIER_TYPE',
        'NATIONAL_IDENTIFIER_NUMBER': 'NATIONAL_IDENTIFIER_NUMBER',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'SOURCE_SYSTEM_OWNER': 'SOURCE_SYSTEM_OWNER',
    },

    # =========================================================================
    # HCM_PERSON_SUPERVISOR_INTF - Supervisor file
    # =========================================================================
    ('HCM_PERSON_SUPERVISOR_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'ACTION': 'ACTION',
        'ACTION_REASON': 'ACTION_REASON',
        'MANAGER_PERSON_NUMBER': 'MANAGER_PERSON_NUMBER',
        'MANAGER_TYPE': 'MANAGER_TYPE',
    },
    ('HCM_PERSON_SUPERVISOR_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'ACTION': 'ACTION',
        'ACTION_REASON': 'ACTION_REASON',
        'EMPLID2': 'MANAGER_PERSON_NUMBER',
        'DESCR': 'DESCR',
        'REPORTS_TO': 'REPORTS_TO',
        'TAX_LOCATION_CD': 'TAX_LOCATION_CD',
        'PAYGROUP': 'PAYGROUP',
        'COMPANY': 'COMPANY',
    },
    ('HCM_PERSON_SUPERVISOR_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'EFFDT': 'EFFECTIVE_START_DATE',
        'ACTION': 'ACTION',
        'ACTION_REASON': 'ACTION_REASON',
        'EMPLID2': 'MANAGER_PERSON_NUMBER',
        'DESCR': 'DESCR',
        'REPORTS_TO': 'REPORTS_TO',
        'TAX_LOCATION_CD': 'TAX_LOCATION_CD',
        'PAYGROUP': 'PAYGROUP',
        'COMPANY': 'COMPANY',
    },
    ('HCM_PERSON_SUPERVISOR_INTF', '911'): {
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'SupervisorPersonNumber': 'MANAGER_PERSON_NUMBER',
    },
    ('HCM_PERSON_SUPERVISOR_INTF', 'KRONOSPOL'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'ASSIGNMENT_NUMBER': 'ASSIGNMENT_NUMBER',
        'LEGAL_ENTITY': 'LEGAL_ENTITY',
        'MANAGER_TYPE': 'MANAGER_TYPE',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'EFFECTIVE_END_DATE': 'EFFECTIVE_END_DATE',
        'ACTION_CODE': 'ACTION_CODE',
        'ACTION_REASON': 'ACTION_REASON',
        'MANAGER_PERSON_NUMBER': 'MANAGER_PERSON_NUMBER',
        'MANAGER_ASSIGNMENT_NUMBER': 'MANAGER_ASSIGNMENT_NUMBER',
        'MANAGER_LEGAL_ENTITY': 'MANAGER_LEGAL_ENTITY',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },

    # =========================================================================
    # HCM_PERSON_EMAIL_INTF - Email file
    # =========================================================================
    ('HCM_PERSON_EMAIL_INTF', 'RHUM'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'E_ADDR_TYPE': 'EMAIL_TYPE',
        'Email_ADDR': 'EMAIL_ADDRESS',
        'EFFDT': 'EFFECTIVE_START_DATE',
    },
    ('HCM_PERSON_EMAIL_INTF', 'FIMAS'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'E_ADDR_TYPE': 'EMAIL_TYPE',
        'EmailADDR': 'EMAIL_ADDRESS',
        'EFFDT': 'EFFECTIVE_START_DATE',
    },
    ('HCM_PERSON_EMAIL_INTF', 'HACIENDA'): {
        'COUNTRY': 'COUNTRY_CODE',
        'EMPLID': 'PERSON_NUMBER',
        'E_ADDR_TYPE': 'EMAIL_TYPE',
        'EmailADDR': 'EMAIL_ADDRESS',
        'EFFDT': 'EFFECTIVE_START_DATE',
    },
    ('HCM_PERSON_EMAIL_INTF', 'DOE'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EMAIL_TYPE': 'EMAIL_TYPE',
        'EMAIL_ADDRESS': 'EMAIL_ADDRESS',
        'DATE_FROM': 'EFFECTIVE_START_DATE',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
        'X': 'X',
    },
    ('HCM_PERSON_EMAIL_INTF', 'KRONOSPOL'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EMAIL_TYPE': 'EMAIL_TYPE',
        'EMAIL_ADDRESS': 'EMAIL_ADDRESS',
        'EFFECTIVE_START_DATE': 'EFFECTIVE_START_DATE',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'ATTRIBUTE_CATEGORY': 'ATTRIBUTE_CATEGORY',
        'ATTRIBUTE1': 'ATTRIBUTE1',
    },
    ('HCM_PERSON_EMAIL_INTF', 'ADPPOLICIA'): {
        'COUNTRY_CODE': 'COUNTRY_CODE',
        'SWIFT_PERSON_TYPE': 'SWIFT_PERSON_TYPE',
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'EMAIL_TYPE': 'EMAIL_TYPE',
        'DATE_FROM': 'DATE_FROM',
        'DATE_TO': 'DATE_TO',
        'EMAIL_ADDRESS': 'EMAIL_ADDRESS',
        'PRIMARY_FLAG': 'PRIMARY_FLAG',
        'SOURCE_SYSTEM_OWNER': 'SOURCE_SYSTEM_OWNER',
    },

    # =========================================================================
    # HCM_SENIORITY_INTF - Seniority file
    # =========================================================================
    ('HCM_SENIORITY_INTF', 'RHUM'): {
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'SENIORITY_DATE_CODE': 'SENIORITY_DATE_CODE',
        'ENTRY_DATE': 'ENTRY_DATE',
    },
    ('HCM_SENIORITY_INTF', 'FIMAS'): {
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'SENIORITY_DATE_CODE': 'SENIORITY_DATE_CODE',
        'ENTRY_DATE': 'ENTRY_DATE',
    },
    ('HCM_SENIORITY_INTF', 'HACIENDA'): {
        'PERSON_NUMBER': 'PERSON_NUMBER',
        'SENIORITY_DATE_CODE': 'SENIORITY_DATE_CODE',
        'ENTRY_DATE': 'ENTRY_DATE',
    },
}


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def get_aws_secret(secret_name: str, region: str = 'us-east-1') -> str:
    """Retrieve a secret from AWS Secrets Manager."""
    client = boto3.client('secretsmanager', region_name=region)
    response = client.get_secret_value(SecretId=secret_name)

    if 'SecretString' in response:
        return response['SecretString']
    else:
        return response['SecretBinary'].decode('utf-8')


def extract_source_from_filename(filename: str) -> Optional[str]:
    """
    Extract the source system from a filename.

    File naming convention: HCM_{ENTITY}_INTF_{SOURCE}_{DATE}.csv

    Examples:
        HCM_PERSON_ADDRESS_INTF_FIMAS_20251209.csv -> FIMAS
        HCM_PERSON_INTF_RHUM_20251209.csv -> RHUM
        Worker_Assignment_HAC88_20251205.csv -> HACIENDA (via alias)
    """
    try:
        fname_nopath = filename.split('/')[-1].split('\\')[-1]
        parts = fname_nopath.replace('.csv', '').replace('.CSV', '').split('_')

        # Try different positions for source name
        for source_pos in [3, 4, 5]:
            if len(parts) > source_pos:
                raw_source = parts[source_pos].upper()

                # Skip if this looks like a date (all digits)
                if raw_source.isdigit():
                    continue

                # Check if it's a known source or alias
                if raw_source in SOURCE_ALIASES:
                    return SOURCE_ALIASES[raw_source]

        # Fallback: look for known source names anywhere in filename
        filename_upper = fname_nopath.upper()
        for source_name in SOURCE_ALIASES.keys():
            if f'_{source_name}_' in filename_upper or filename_upper.endswith(f'_{source_name}.CSV'):
                return SOURCE_ALIASES[source_name]

    except Exception:
        pass

    return None


def extract_entity_from_filename(filename: str) -> Optional[str]:
    """
    Extract the entity type from a filename.

    Examples:
        HCM_PERSON_ADDRESS_INTF_FIMAS_20251209.csv -> HCM_PERSON_ADDRESS_INTF
        HCM_PERSON_INTF_RHUM_20251209.csv -> HCM_PERSON_INTF
    """
    fname_nopath = filename.split('/')[-1].split('\\')[-1].upper()

    # Known entity patterns
    entities = [
        'HCM_PERSON_ASSIGNMENT_INTF',
        'HCM_PERSON_ADDRESS_INTF',
        'HCM_PERSON_SUPERVISOR_INTF',
        'HCM_PERSON_EMAIL_INTF',
        'HCM_PERSON_NAME_INTF',
        'HCM_PERSON_NID_INTF',
        'HCM_PERSON_INTF',
        'HCM_SENIORITY_INTF',
        'HCM_EXTERNAL_IDENTIFIER_INTF',
        'HCM_DEPARTMENT_INTF',
        'HCM_JOBS_INTF',
        'HCM_LOCATION_INTF',
        'HCM_EMPLOYEES_TO_SYNCH',
    ]

    for entity in entities:
        if entity in fname_nopath:
            return entity

    return None


def extract_table_name_from_filename(filename: str) -> Tuple[Optional[str], Optional[str]]:
    """
    Extract the table name and date portion from a filename.

    Returns:
        Tuple of (table_name, date_portion) or (None, None) if parsing fails
    """
    # Remove extension
    name = filename.rsplit('.', 1)[0] if '.' in filename else filename

    # Pattern: everything before the last underscore followed by digits
    match = re.match(r'^(.+?)_(\d{8,14})$', name)

    if match:
        table_name = match.group(1).upper()
        date_portion = match.group(2)
        return table_name, date_portion

    return None, None


def sanitize_column_name(name: str) -> str:
    """Sanitize a column name for SQL Server."""
    sanitized = re.sub(r'[^a-zA-Z0-9_]', '_', name)
    if sanitized and sanitized[0].isdigit():
        sanitized = '_' + sanitized
    return sanitized[:128] if sanitized else 'COLUMN'


def get_column_mapping(entity: str, source: str) -> Optional[Dict[str, str]]:
    """
    Get the column mapping for a specific entity and source combination.

    Args:
        entity: Entity type (e.g., 'HCM_PERSON_INTF')
        source: Source system (e.g., 'FIMAS')

    Returns:
        Dict mapping CSV column names to DB column names, or None if not found
    """
    key = (entity, source)
    return COLUMN_MAPPINGS.get(key)


def get_expected_headers(entity: str, source: str) -> Optional[List[str]]:
    """
    Get the expected CSV headers for a specific entity and source combination.

    Args:
        entity: Entity type (e.g., 'HCM_PERSON_INTF')
        source: Source system (e.g., 'FIMAS')

    Returns:
        List of expected CSV column names, or None if not found
    """
    key = (entity, source)
    return EXPECTED_CSV_HEADERS.get(key)


def validate_csv_headers(
    actual_headers: List[str],
    entity: str,
    source: str,
    strict: bool = False
) -> Dict:
    """
    Validate CSV headers against expected headers for an entity/source combination.

    This function checks that all REQUIRED headers are present in the CSV file.
    Extra columns in the CSV are allowed (they will be skipped during loading).

    Args:
        actual_headers: List of headers found in the CSV file
        entity: Entity type (e.g., 'HCM_PERSON_INTF')
        source: Source system (e.g., 'FIMAS')
        strict: If True, require EXACT match (no extra columns allowed)

    Returns:
        Dict with validation results:
            - valid: bool - True if validation passed
            - entity: str - The entity type
            - source: str - The source system
            - expected_headers: List[str] - Expected headers (or None if not defined)
            - actual_headers: List[str] - Headers found in CSV
            - missing_headers: List[str] - Required headers not found in CSV
            - extra_headers: List[str] - Headers in CSV but not in expected list
            - error: str - Error message if validation failed (or None)
    """
    result = {
        'valid': False,
        'entity': entity,
        'source': source,
        'expected_headers': None,
        'actual_headers': actual_headers,
        'missing_headers': [],
        'extra_headers': [],
        'error': None
    }

    # Get expected headers
    expected = get_expected_headers(entity, source)

    if expected is None:
        # No expected headers defined for this entity/source combination
        # This is not an error - just means we don't have validation rules
        result['valid'] = True
        result['error'] = f'No header validation rules defined for entity={entity}, source={source} (allowing all headers)'
        return result

    result['expected_headers'] = expected

    # Normalize headers for comparison (strip whitespace, handle case)
    actual_upper = {h.strip().upper(): h.strip() for h in actual_headers}
    expected_upper = {h.upper(): h for h in expected}

    # Find missing required headers
    missing = []
    for exp_header in expected:
        if exp_header.upper() not in actual_upper:
            missing.append(exp_header)

    result['missing_headers'] = missing

    # Find extra headers (in actual but not in expected)
    extra = []
    for actual_header in actual_headers:
        if actual_header.strip().upper() not in expected_upper:
            extra.append(actual_header.strip())

    result['extra_headers'] = extra

    # Determine if validation passed
    if missing:
        result['valid'] = False
        result['error'] = f'Missing required CSV headers: {", ".join(missing)}'
    elif strict and extra:
        result['valid'] = False
        result['error'] = f'Unexpected extra CSV headers (strict mode): {", ".join(extra)}'
    else:
        result['valid'] = True
        if extra:
            result['error'] = f'Extra columns will be ignored: {", ".join(extra)}'

    return result


def validate_file_headers(
    s3_client,
    bucket: str,
    s3_key: str,
    filename: str,
    strict: bool = False
) -> Dict:
    """
    Validate headers of a CSV file stored in S3.

    Args:
        s3_client: Boto3 S3 client
        bucket: S3 bucket name
        s3_key: S3 object key
        filename: Original filename (used to extract entity/source)
        strict: If True, require exact header match

    Returns:
        Dict with validation results (same format as validate_csv_headers)
    """
    result = {
        'valid': False,
        'filename': filename,
        's3_key': s3_key,
        'entity': None,
        'source': None,
        'expected_headers': None,
        'actual_headers': [],
        'missing_headers': [],
        'extra_headers': [],
        'error': None
    }

    try:
        # Extract entity and source from filename
        entity = extract_entity_from_filename(filename)
        source = extract_source_from_filename(filename)

        result['entity'] = entity
        result['source'] = source

        if not entity:
            result['error'] = f'Could not determine entity type from filename: {filename}'
            return result

        if not source:
            result['error'] = f'Could not determine source from filename: {filename}'
            return result

        # Read just the first line (headers) from S3
        headers, _ = read_csv_data(s3_client, bucket, s3_key)
        result['actual_headers'] = headers

        if not headers:
            result['error'] = 'No headers found in CSV file'
            return result

        # Validate headers
        validation = validate_csv_headers(headers, entity, source, strict)

        # Merge validation results
        result.update(validation)
        result['filename'] = filename
        result['s3_key'] = s3_key

        return result

    except Exception as e:
        result['error'] = f'Error reading file headers: {str(e)}'
        return result


def parse_connection_string(conn_str: str) -> Dict:
    """Parse ODBC connection string into components for pymssql."""
    params = {}
    for part in conn_str.split(';'):
        if '=' in part:
            key, value = part.split('=', 1)
            key = key.strip().upper()
            value = value.strip()
            if key == 'SERVER':
                if ',' in value:
                    server, port = value.split(',')
                    params['server'] = server.strip()
                    params['port'] = int(port.strip())
                else:
                    params['server'] = value
                    params['port'] = 1433
            elif key == 'DATABASE':
                params['database'] = value
            elif key == 'UID':
                params['user'] = value
            elif key == 'PWD':
                params['password'] = value
    return params


def read_csv_data(s3_client, bucket: str, key: str) -> Tuple[List[str], List[List[str]]]:
    """Read CSV data from S3."""
    response = s3_client.get_object(Bucket=bucket, Key=key)
    content = response['Body'].read().decode('utf-8', errors='ignore')

    reader = csv.reader(io.StringIO(content))
    rows = list(reader)

    if not rows:
        return [], []

    headers = [h.strip().strip('"').strip() for h in rows[0]]
    data_rows = []

    for row in rows[1:]:
        if len(row) < len(headers):
            row = row + [''] * (len(headers) - len(row))
        elif len(row) > len(headers):
            row = row[:len(headers)]

        cleaned_row = [str(val).strip() if val else '' for val in row]
        data_rows.append(cleaned_row)

    return headers, data_rows


def get_table_columns(cursor, table_name: str) -> List[str]:
    """Get the list of column names from a database table."""
    safe_table_name = sanitize_column_name(table_name)
    cursor.execute(f"""
        SELECT COLUMN_NAME
        FROM INFORMATION_SCHEMA.COLUMNS
        WHERE TABLE_NAME = '{safe_table_name}' AND TABLE_SCHEMA = 'dbo'
        ORDER BY ORDINAL_POSITION
    """)
    return [row[0].upper() for row in cursor.fetchall()]


# =============================================================================
# MAIN LOADING FUNCTION
# =============================================================================

def load_file_to_sql(
    s3_client,
    connection_string: str,
    bucket: str,
    s3_key: str,
    table_name: str,
    filename: str,
    clear_existing: bool = True
) -> Dict:
    """
    Load a single CSV file from S3 into an existing SQL Server table.
    Uses proper column mapping based on entity type and source system.
    """
    import pymssql

    safe_table_name = sanitize_column_name(table_name)

    result = {
        'table_name': table_name,
        's3_key': s3_key,
        'filename': filename,
        'success': False,
        'rows_loaded': 0,
        'error': None,
        'error_type': None,
        'columns_matched': 0,
        'columns_skipped': [],
        'csv_columns': [],
        'db_columns': [],
    }

    try:
        # Extract entity and source from filename
        entity = extract_entity_from_filename(filename)
        source = extract_source_from_filename(filename)

        result['entity'] = entity
        result['source'] = source

        if not entity:
            result['error'] = f'Could not determine entity type from filename: {filename}'
            result['error_type'] = 'INVALID_FILENAME'
            return result

        if not source:
            result['error'] = f'Could not determine source from filename: {filename}'
            result['error_type'] = 'INVALID_FILENAME'
            return result

        # Get column mapping for this entity/source combination
        column_mapping = get_column_mapping(entity, source)

        if not column_mapping:
            result['error'] = f'No column mapping defined for entity={entity}, source={source}'
            result['error_type'] = 'NO_MAPPING'
            return result

        # Read CSV data
        headers, rows = read_csv_data(s3_client, bucket, s3_key)
        result['csv_columns'] = headers
        result['csv_row_count'] = len(rows)

        if not headers:
            result['error'] = 'No headers found in CSV'
            result['error_type'] = 'NO_HEADERS'
            return result

        # =====================================================================
        # HEADER VALIDATION - Check CSV headers match expected format
        # =====================================================================
        header_validation = validate_csv_headers(headers, entity, source, strict=False)
        result['header_validation'] = header_validation

        if not header_validation['valid']:
            result['error'] = f'Header validation failed: {header_validation["error"]}'
            result['error_type'] = 'HEADER_VALIDATION_FAILED'
            result['missing_headers'] = header_validation.get('missing_headers', [])
            result['expected_headers'] = header_validation.get('expected_headers', [])
            return result

        # Log any extra headers that will be skipped
        if header_validation.get('extra_headers'):
            result['extra_headers_warning'] = f'Extra columns will be ignored: {header_validation["extra_headers"]}'

        # Parse connection string and connect
        conn_params = parse_connection_string(connection_string)
        with pymssql.connect(
            server=conn_params['server'],
            port=conn_params.get('port', 1433),
            user=conn_params['user'],
            password=conn_params['password'],
            database=conn_params['database'],
            tds_version='7.3',
            autocommit=False
        ) as conn:
            cursor = conn.cursor()

            # Set session options for proper date handling
            cursor.execute("SET LANGUAGE us_english")
            cursor.execute("SET DATEFORMAT mdy")

            # Get actual database columns for this table
            db_columns = get_table_columns(cursor, table_name)
            result['db_columns'] = db_columns

            if not db_columns:
                result['error'] = f'Table {table_name} not found in database or has no columns'
                result['error_type'] = 'TABLE_NOT_FOUND'
                return result

            # Build column index mapping: csv_index -> (csv_col, db_col)
            db_cols_upper = {c.upper(): c for c in db_columns}
            col_indices = []  # List of (csv_index, db_column_name)
            skipped_cols = []
            mapping_details = []  # Debug: show exactly what was mapped

            # Track which DB columns are already mapped (to prevent duplicates)
            mapped_db_cols = set()

            for i, csv_col in enumerate(headers):
                csv_col_clean = csv_col.strip()

                # Check if this CSV column has a mapping defined
                if csv_col_clean in column_mapping:
                    db_col = column_mapping[csv_col_clean]
                    # Verify the DB column exists
                    if db_col.upper() in db_cols_upper:
                        actual_db_col = db_cols_upper[db_col.upper()]
                        if actual_db_col.upper() not in mapped_db_cols:
                            col_indices.append((i, actual_db_col))
                            mapped_db_cols.add(actual_db_col.upper())
                            mapping_details.append(f"{csv_col_clean} -> {db_col} (mapped)")
                        else:
                            skipped_cols.append(f"{csv_col_clean} (mapped to {db_col} but DB column already mapped)")
                    else:
                        skipped_cols.append(f"{csv_col_clean} (mapped to {db_col} but not in DB)")
                elif csv_col_clean.upper() in db_cols_upper:
                    # Direct match - but only if DB column not already mapped
                    actual_db_col = db_cols_upper[csv_col_clean.upper()]
                    if actual_db_col.upper() not in mapped_db_cols:
                        col_indices.append((i, actual_db_col))
                        mapped_db_cols.add(actual_db_col.upper())
                        mapping_details.append(f"{csv_col_clean} -> {csv_col_clean} (direct)")
                    else:
                        skipped_cols.append(f"{csv_col_clean} (direct match but DB column already mapped via another CSV column)")
                else:
                    skipped_cols.append(csv_col_clean)

            # Handle dual-mappings: CSV columns that map to multiple DB columns
            # These are specified with __ALSO__ syntax: 'SOURCE_COL__ALSO__TARGET_COL': 'TARGET_COL'
            # This allows a single CSV column to populate multiple DB columns
            headers_upper = {h.strip().upper(): idx for idx, h in enumerate(headers)}
            for mapping_key, db_col in column_mapping.items():
                if '__ALSO__' in mapping_key:
                    # Parse: 'EMPL_CLASS__ALSO__WORKER_CATEGORY' -> source='EMPL_CLASS', target='WORKER_CATEGORY'
                    source_csv_col = mapping_key.split('__ALSO__')[0].strip()
                    if source_csv_col.upper() in headers_upper:
                        csv_idx = headers_upper[source_csv_col.upper()]
                        if db_col.upper() in db_cols_upper:
                            actual_db_col = db_cols_upper[db_col.upper()]
                            if actual_db_col.upper() not in mapped_db_cols:
                                col_indices.append((csv_idx, actual_db_col))
                                mapped_db_cols.add(actual_db_col.upper())
                                mapping_details.append(f"{source_csv_col} -> {db_col} (dual-mapped via __ALSO__)")

            result['columns_matched'] = len(col_indices)
            result['columns_skipped'] = skipped_cols
            result['mapping_details'] = mapping_details
            result['column_mapping_used'] = column_mapping
            result['db_cols_upper'] = list(db_cols_upper.keys())

            if not col_indices:
                result['error'] = f'No CSV columns could be mapped to database columns'
                result['error_type'] = 'COLUMN_MISMATCH'
                return result

            # Clear existing data if requested (but not for RHUM - append mode)
            if clear_existing and source != 'RHUM':
                cursor.execute(f"DELETE FROM dbo.[{safe_table_name}]")
                conn.commit()

            # =================================================================
            # DEDUPLICATION: Remove duplicate rows for HCM_PERSON_INTF and
            # HCM_PERSON_NID_INTF tables by PERSON_NUMBER column.
            # The stored procedure's INSERT INTO HCM_PERSON_LEGACY_TO_ORACLE_NUMBER
            # fails with PRIMARY KEY violation if the source table has duplicate
            # PERSON_NUMBERs. The DOE source uses DISTINCT but HACIENDA doesn't.
            # =================================================================
            dedup_entities = ['HCM_PERSON_INTF', 'HCM_PERSON_NID_INTF']
            original_row_count = len(rows)

            if entity in dedup_entities and rows:
                # Find the index of the PERSON_NUMBER column in the mapped columns
                person_number_idx = None
                for mapped_idx, (csv_idx, db_col) in enumerate(col_indices):
                    if db_col.upper() == 'PERSON_NUMBER':
                        person_number_idx = csv_idx
                        break

                if person_number_idx is not None:
                    # Deduplicate rows by PERSON_NUMBER, keeping the first occurrence
                    seen_person_numbers = set()
                    unique_rows = []
                    duplicate_count = 0
                    duplicate_person_numbers = []

                    for row in rows:
                        person_number = row[person_number_idx] if person_number_idx < len(row) else ''
                        person_number_clean = str(person_number).strip()

                        if person_number_clean not in seen_person_numbers:
                            seen_person_numbers.add(person_number_clean)
                            unique_rows.append(row)
                        else:
                            duplicate_count += 1
                            if len(duplicate_person_numbers) < 10:
                                duplicate_person_numbers.append(person_number_clean)

                    rows = unique_rows

                    if duplicate_count > 0:
                        result['deduplication'] = {
                            'original_rows': original_row_count,
                            'unique_rows': len(rows),
                            'duplicates_removed': duplicate_count,
                            'sample_duplicate_person_numbers': duplicate_person_numbers
                        }

            # Insert data
            if rows:
                matched_db_cols = [col_info[1] for col_info in col_indices]
                column_names = ", ".join(f"[{col}]" for col in matched_db_cols)
                placeholders = ", ".join(["%s"] * len(matched_db_cols))
                insert_sql = f"INSERT INTO dbo.[{safe_table_name}] ({column_names}) VALUES ({placeholders})"

                batch_size = 1000
                rows_inserted = 0
                failed_rows = []

                for i in range(0, len(rows), batch_size):
                    batch = rows[i:i + batch_size]
                    filtered_batch = [
                        tuple(row[idx] if idx < len(row) else '' for idx, _ in col_indices)
                        for row in batch
                    ]
                    try:
                        cursor.executemany(insert_sql, filtered_batch)
                        rows_inserted += len(filtered_batch)
                    except Exception as batch_error:
                        # Try one by one to identify problem rows
                        for row_idx, row_data in enumerate(filtered_batch):
                            try:
                                cursor.execute(insert_sql, row_data)
                                rows_inserted += 1
                            except Exception as row_error:
                                actual_row_num = i + row_idx + 2
                                failed_rows.append({
                                    'row_number': actual_row_num,
                                    'error': str(row_error),
                                })
                                if len(failed_rows) >= 10:
                                    break
                        if len(failed_rows) >= 10:
                            break

                conn.commit()
                result['rows_loaded'] = rows_inserted

                if failed_rows:
                    result['failed_rows'] = failed_rows
                    result['error'] = f'Some rows failed to insert: {len(failed_rows)} errors'
                    result['error_type'] = 'DATA_ERROR'
                    result['success'] = rows_inserted > 0
                    return result

            result['success'] = True

    except Exception as e:
        error_str = str(e)
        result['error'] = error_str

        if 'truncat' in error_str.lower():
            result['error_type'] = 'DATA_TRUNCATION'
        elif 'conversion' in error_str.lower() or 'convert' in error_str.lower():
            result['error_type'] = 'DATA_CONVERSION'
        elif 'constraint' in error_str.lower():
            result['error_type'] = 'CONSTRAINT_VIOLATION'
        elif 'permission' in error_str.lower() or 'denied' in error_str.lower():
            result['error_type'] = 'PERMISSION_ERROR'
        else:
            result['error_type'] = 'UNKNOWN_ERROR'

    return result


def identify_files_to_load(files: List[Dict]) -> Dict[str, Dict]:
    """
    Identify the newest version of each file type to load.
    """
    table_files = {}

    for file_info in files:
        filename = file_info.get('filename', '')
        table_name, date_portion = extract_table_name_from_filename(filename)

        if not table_name or not date_portion:
            continue

        if table_name not in table_files:
            table_files[table_name] = []

        table_files[table_name].append({
            **file_info,
            'table_name': table_name,
            'date_portion': date_portion
        })

    result = {}
    for table_name, files_list in table_files.items():
        sorted_files = sorted(files_list, key=lambda x: x['date_portion'], reverse=True)
        result[table_name] = sorted_files[0]

    return result


# =============================================================================
# SQLSERVERLOADER CLASS (Used by full_pipeline.py)
# =============================================================================

class SqlServerLoader:
    """
    SQL Server loader class for use by the full pipeline orchestrator.
    """

    def __init__(
        self,
        bucket: str = None,
        secret_name: str = 'Hacienda_ERP_Test_MSSQL_text',
        database_override: Optional[str] = None,
        region: str = 'us-east-1'
    ):
        import os
        self.bucket = bucket or os.environ.get('S3_BUCKET', 'hacienda-sftp-downloads')
        self.secret_name = secret_name
        self.database_override = database_override
        self.region = region
        self.s3_client = boto3.client('s3', region_name=region)

    def load_files(
        self,
        files: List[Dict],
        drop_existing: bool = False
    ) -> Dict:
        """
        Load multiple files to SQL Server.

        Args:
            files: List of dicts with 'filename' and 's3_key'
            drop_existing: Whether to clear existing data (True = clear)

        Returns:
            Dict with load results
        """
        # Get connection string
        connection_string = get_aws_secret(self.secret_name, self.region)

        # Apply database override if specified
        if self.database_override:
            # Modify connection string to use different database
            parts = connection_string.split(';')
            new_parts = []
            for part in parts:
                if part.strip().upper().startswith('DATABASE='):
                    new_parts.append(f'Database={self.database_override}')
                else:
                    new_parts.append(part)
            connection_string = ';'.join(new_parts)

        # Identify files to load
        files_to_load = identify_files_to_load(files)

        results = {
            'total_tables': len(files_to_load),
            'loaded_tables': 0,
            'failed_tables': 0,
            'total_rows': 0,
            'table_results': [],
            'detailed_failures': []
        }

        for table_name, file_info in files_to_load.items():
            s3_key = file_info.get('s3_key') or file_info.get('key', '')
            filename = file_info.get('filename', '')

            load_result = load_file_to_sql(
                s3_client=self.s3_client,
                connection_string=connection_string,
                bucket=self.bucket,
                s3_key=s3_key,
                table_name=table_name,
                filename=filename,
                clear_existing=drop_existing
            )

            load_result['source_file'] = filename
            results['table_results'].append(load_result)

            if load_result['success']:
                results['loaded_tables'] += 1
                results['total_rows'] += load_result.get('rows_loaded', 0)
            else:
                results['failed_tables'] += 1
                results['detailed_failures'].append(load_result)

        return results


# =============================================================================
# LAMBDA HANDLERS
# =============================================================================

def load_to_sql_handler(event, context):
    """Lambda handler for loading validated files to SQL Server."""
    import os
    import json

    try:
        if 'body' in event and event['body']:
            body = json.loads(event['body']) if isinstance(event['body'], str) else event['body']
        else:
            body = event

        files = body.get('files', [])
        bucket = body.get('bucket', os.environ.get('S3_BUCKET', 'hacienda-sftp-downloads'))
        clear_existing = body.get('clear_existing', True)
        database_override = body.get('database_override')

        if not files:
            return {
                'statusCode': 400,
                'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
                'body': json.dumps({'error': 'No files provided'})
            }

        loader = SqlServerLoader(
            bucket=bucket,
            database_override=database_override
        )

        results = loader.load_files(files=files, drop_existing=clear_existing)

        return {
            'statusCode': 200,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps(results, default=str)
        }

    except Exception as e:
        return {
            'statusCode': 500,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({'error': str(e)})
        }


def validate_headers_handler(event, context):
    """
    Lambda handler for validating CSV headers without loading data.

    Useful for pre-flight checks before running the full pipeline.

    Expected event format:
    {
        "files": [
            {"filename": "HCM_PERSON_INTF_FIMAS_20251209.csv", "s3_key": "uploads/..."},
            ...
        ],
        "bucket": "hacienda-sftp-downloads" (optional)
    }
    """
    import os
    import json

    try:
        if 'body' in event and event['body']:
            body = json.loads(event['body']) if isinstance(event['body'], str) else event['body']
        else:
            body = event

        files = body.get('files', [])
        bucket = body.get('bucket', os.environ.get('S3_BUCKET', 'hacienda-sftp-downloads'))

        if not files:
            return {
                'statusCode': 400,
                'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
                'body': json.dumps({'error': 'No files provided'})
            }

        s3_client = boto3.client('s3', region_name='us-east-1')

        results = {
            'total_files': len(files),
            'valid_files': 0,
            'invalid_files': 0,
            'validation_results': [],
            'version': SQL_TABLE_LOADER_VERSION
        }

        for file_info in files:
            filename = file_info.get('filename', '')
            s3_key = file_info.get('s3_key') or file_info.get('key', '')

            validation = validate_file_headers(
                s3_client=s3_client,
                bucket=bucket,
                s3_key=s3_key,
                filename=filename,
                strict=False
            )

            results['validation_results'].append(validation)

            if validation['valid']:
                results['valid_files'] += 1
            else:
                results['invalid_files'] += 1

        return {
            'statusCode': 200,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps(results, default=str)
        }

    except Exception as e:
        return {
            'statusCode': 500,
            'headers': {'Content-Type': 'application/json', 'Access-Control-Allow-Origin': '*'},
            'body': json.dumps({'error': str(e)})
        }
